apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          subPath: m2
          mountPath: /root/.m2
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          subPath: docker
          mountPath: /var/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.3.4
      command:
        - cat
      tty: true
  serviceAccountName: tiller
  volumes:
    - name: dockersock
      persistentVolumeClaim:
        claimName: opspvc        
    - name: m2
      persistentVolumeClaim:
        claimName: opspvc        
