image:
  repository: tlchow/k8sdemo
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 8090

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host:
      paths:
        - /k8sdemo
        
serviceAccount:
  create: false
  
autoscaling:
  enabled: false