image:
  repository: tlchow/kubernetescicddemo
  tag: latest
  pullPolicy: Always

name: "kubernetescicddemo"
domain: "home"

replicaCount: 1

service:
  port: 8090

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host:
      paths:
        - /kubernetescicddemo